version: '2'

services:
  api:
    image: ${PRODUCTION_IMAGE}
    networks: ['bicing-statistics-api-data']
    ports: ['9090:9090']
    restart: 'always'
    volumes: ['./.env:/var/www/bicing-prediction-api/.env', './var:/var/www/bicing-prediction-api/var']

networks:
  bicing-statistics-api-data:
    external: true
