swagger: "2.0"

info:
  version: 1.0.0
  title: Prediction Station Availability Service
  license:
    name: MIT

basePath: /1.0

schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /stations/{station_id}:
    get:
      operationId: user_interface.rest.flask.action.flask_predict_by_station_id_action.get
      parameters:
        - name: station_id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: 'Predict number of bikes available at in a time slot for a station'

  /forecasts:
    post:
      operationId: user_interface.rest.flask.action.flask_predict_by_station_ids_action.post
      parameters:
        - in: body
          name: forecast
          required: true
          schema:
            $ref: '#/definitions/Forecast'
      responses:
        '200':
          description: 'Forecast state for many stations in '

definitions:
  Forecast:
    type: object
    required:
      - station_ids
      - filter
    properties:
      station_ids:
        $ref: '#/definitions/StationIds'
      filter:
        $ref: '#/definitions/Filter'
  Filter:
    type: string
  StationIds:
    type: array
    items:
      type: string
      format: uuid
